---
title: "ufc_analysis_r"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Load the data and Tidyverse library
```{r}
library(tidyverse)
library(ggrepel)
file = "data/ufc_clean.csv"
data = read.csv(file, stringsAsFactors = FALSE)
summary(data)
```
## Plot Buyrate over time
```{r}
knitr::opts_chunk$set(fig.width=20, fig.height=12)

# first, filter out all non main events

main_events <- subset(data, Main_Event == 1)
main_events$Date <- as.Date(main_events$Date, format= "%Y-%m-%d")
past_10y <- subset(main_events, Date > "2008-01-01" & Date < "2019-01-01")

# if no title, set as event number
past_10y$Title <- ifelse(past_10y$Title == "", past_10y$Event, past_10y$Title)

# get rid of titles for everything except for top 10 buyrates
top10_ix <- rownames(past_10y[order(past_10y$Buyrate, decreasing = TRUE),][1:10,])
past_10y$Title[!(rownames(past_10y) %in% top10_ix)] <- ""

p <- ggplot(data = past_10y, 
            mapping = aes(x = Date, y= Buyrate, group = 1))

p + geom_line() +
    geom_smooth(method = 'lm') +
    geom_text_repel(label = past_10y$Title)  +
    scale_y_continuous(labels = scales::comma) +
    geom_point(color = 'red', alpha = ifelse(past_10y$Title == "", 0, 1)) +
    labs(title = "UFC Pay-Per-View Buyrates, 2008-2018",
         subtitle = "Top 10 Events Highlighted & Linear Trendline",
         y = "Pay-Per-View Buys")

ggsave("ppv-buys.png")
```
Plot done